modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
authors="Fadiese" #optional

[[mods]] #mandatory
modId="eldritchgolems" #mandatory
version="0.1.0" #mandatory
displayName="EldritchGolems" #mandatory
description='''
New golems. For the Greater Good.
'''

[[dependencies.eldritchgolems]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.eldritchgolems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"